// auto generated 2026-08-28 10:23:32.360917 +0200 CEST m=+0.062676376

package registry

import "github.com/nats-io/jsm.go/api"

func init() {
	RegisterTypeFactory("io.nats.jetstream.api.v1.account_info_response", func() any { return &api.JSApiAccountInfoResponse{} })
	RegisterResponseSubjectType(api.JSApiAccountInfoPrefix, "io.nats.jetstream.api.v1.account_info_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.account_purge_response", func() any { return &api.JSApiAccountPurgeResponse{} })
	RegisterResponseSubjectType(api.JSApiAccountPurgePrefix, "io.nats.jetstream.api.v1.account_purge_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_configuration", func() any { return &api.ConsumerConfig{} })
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_create_request", func() any { return &api.JSApiConsumerCreateRequest{} })
	RegisterRequestSubjectType(api.JSApiConsumerCreateWithNamePrefix, "io.nats.jetstream.api.v1.consumer_create_request")
	RegisterWildcardType(api.JSApiConsumerCreateWithName, "io.nats.jetstream.api.v1.consumer_create_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_create_response", func() any { return &api.JSApiConsumerCreateResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerCreatePrefix, "io.nats.jetstream.api.v1.consumer_create_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_delete_response", func() any { return &api.JSApiConsumerDeleteResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerDeletePrefix, "io.nats.jetstream.api.v1.consumer_delete_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_getnext_request", func() any { return &api.JSApiConsumerGetNextRequest{} })
	RegisterRequestSubjectType(api.JSApiRequestNextPrefix, "io.nats.jetstream.api.v1.consumer_getnext_request")
	RegisterWildcardType(api.JSApiRequestNext, "io.nats.jetstream.api.v1.consumer_getnext_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_info_request", func() any { return &api.JSApiConsumerInfoRequest{} })
	RegisterRequestSubjectType(api.JSApiConsumerInfoPrefix, "io.nats.jetstream.api.v1.consumer_info_request")
	RegisterWildcardType(api.JSApiConsumerInfo, "io.nats.jetstream.api.v1.consumer_info_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_info_response", func() any { return &api.JSApiConsumerInfoResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerInfoPrefix, "io.nats.jetstream.api.v1.consumer_info_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_leader_stepdown_request", func() any { return &api.JSApiConsumerLeaderStepdownRequest{} })
	RegisterRequestSubjectType(api.JSApiConsumerLeaderStepDownPrefix, "io.nats.jetstream.api.v1.consumer_leader_stepdown_request")
	RegisterWildcardType(api.JSApiConsumerLeaderStepDown, "io.nats.jetstream.api.v1.consumer_leader_stepdown_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_leader_stepdown_response", func() any { return &api.JSApiConsumerLeaderStepDownResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerLeaderStepDownPrefix, "io.nats.jetstream.api.v1.consumer_leader_stepdown_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_list_request", func() any { return &api.JSApiConsumerListRequest{} })
	RegisterRequestSubjectType(api.JSApiConsumerListPrefix, "io.nats.jetstream.api.v1.consumer_list_request")
	RegisterWildcardType(api.JSApiConsumerList, "io.nats.jetstream.api.v1.consumer_list_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_list_response", func() any { return &api.JSApiConsumerListResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerListPrefix, "io.nats.jetstream.api.v1.consumer_list_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_names_request", func() any { return &api.JSApiConsumerNamesRequest{} })
	RegisterRequestSubjectType(api.JSApiConsumerNamesPrefix, "io.nats.jetstream.api.v1.consumer_names_request")
	RegisterWildcardType(api.JSApiConsumerNames, "io.nats.jetstream.api.v1.consumer_names_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_names_response", func() any { return &api.JSApiConsumerNamesResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerNamesPrefix, "io.nats.jetstream.api.v1.consumer_names_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_pause_request", func() any { return &api.JSApiConsumerPauseRequest{} })
	RegisterRequestSubjectType(api.JSApiConsumerPausePrefix, "io.nats.jetstream.api.v1.consumer_pause_request")
	RegisterWildcardType(api.JSApiConsumerPause, "io.nats.jetstream.api.v1.consumer_pause_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_pause_response", func() any { return &api.JSApiConsumerPauseResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerPausePrefix, "io.nats.jetstream.api.v1.consumer_pause_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_reset_request", func() any { return &api.JSApiConsumerResetRequest{} })
	RegisterRequestSubjectType(api.JSApiConsumerResetPrefix, "io.nats.jetstream.api.v1.consumer_reset_request")
	RegisterWildcardType(api.JSApiConsumerReset, "io.nats.jetstream.api.v1.consumer_reset_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_reset_response", func() any { return &api.JSApiConsumerResetResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerResetPrefix, "io.nats.jetstream.api.v1.consumer_reset_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_unpin_request", func() any { return &api.JSApiConsumerUnpinRequest{} })
	RegisterRequestSubjectType(api.JSApiConsumerUnpinPrefix, "io.nats.jetstream.api.v1.consumer_unpin_request")
	RegisterWildcardType(api.JSApiConsumerUnpin, "io.nats.jetstream.api.v1.consumer_unpin_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.consumer_unpin_response", func() any { return &api.JSApiConsumerUnpinResponse{} })
	RegisterResponseSubjectType(api.JSApiConsumerUnpinPrefix, "io.nats.jetstream.api.v1.consumer_unpin_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.meta_leader_stepdown_request", func() any { return &api.JSApiLeaderStepDownRequest{} })
	RegisterRequestSubjectType(api.JSApiLeaderStepDownPrefix, "io.nats.jetstream.api.v1.meta_leader_stepdown_request")
	RegisterWildcardType(api.JSApiLeaderStepDown, "io.nats.jetstream.api.v1.meta_leader_stepdown_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.meta_leader_stepdown_response", func() any { return &api.JSApiLeaderStepDownResponse{} })
	RegisterResponseSubjectType(api.JSApiLeaderStepDownPrefix, "io.nats.jetstream.api.v1.meta_leader_stepdown_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.meta_server_remove_request", func() any { return &api.JSApiMetaServerRemoveRequest{} })
	RegisterRequestSubjectType(api.JSApiServerRemovePrefix, "io.nats.jetstream.api.v1.meta_server_remove_request")
	RegisterWildcardType(api.JSApiServerRemove, "io.nats.jetstream.api.v1.meta_server_remove_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.meta_server_remove_response", func() any { return &api.JSApiMetaServerRemoveResponse{} })
	RegisterResponseSubjectType(api.JSApiServerRemovePrefix, "io.nats.jetstream.api.v1.meta_server_remove_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.pub_ack_response", func() any { return &api.JSPubAckResponse{} })
	RegisterResponseSubjectType(api.JSAckPrefix, "io.nats.jetstream.api.v1.pub_ack_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_configuration", func() any { return &api.StreamConfig{} })
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_create_request", func() any { return &api.JSApiStreamCreateRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamCreatePrefix, "io.nats.jetstream.api.v1.stream_create_request")
	RegisterWildcardType(api.JSApiStreamCreate, "io.nats.jetstream.api.v1.stream_create_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_create_response", func() any { return &api.JSApiStreamCreateResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamCreatePrefix, "io.nats.jetstream.api.v1.stream_create_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_delete_response", func() any { return &api.JSApiStreamDeleteResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamDeletePrefix, "io.nats.jetstream.api.v1.stream_delete_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_info_request", func() any { return &api.JSApiStreamInfoRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamInfoPrefix, "io.nats.jetstream.api.v1.stream_info_request")
	RegisterWildcardType(api.JSApiStreamInfo, "io.nats.jetstream.api.v1.stream_info_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_info_response", func() any { return &api.JSApiStreamInfoResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamInfoPrefix, "io.nats.jetstream.api.v1.stream_info_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_leader_stepdown_request", func() any { return &api.JSApiStreamLeaderStepDownRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamLeaderStepDownPrefix, "io.nats.jetstream.api.v1.stream_leader_stepdown_request")
	RegisterWildcardType(api.JSApiStreamLeaderStepDown, "io.nats.jetstream.api.v1.stream_leader_stepdown_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_leader_stepdown_response", func() any { return &api.JSApiStreamLeaderStepDownResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamLeaderStepDownPrefix, "io.nats.jetstream.api.v1.stream_leader_stepdown_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_list_request", func() any { return &api.JSApiStreamListRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamListPrefix, "io.nats.jetstream.api.v1.stream_list_request")
	RegisterWildcardType(api.JSApiStreamList, "io.nats.jetstream.api.v1.stream_list_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_list_response", func() any { return &api.JSApiStreamListResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamListPrefix, "io.nats.jetstream.api.v1.stream_list_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_msg_delete_request", func() any { return &api.JSApiMsgDeleteRequest{} })
	RegisterRequestSubjectType(api.JSApiMsgDeletePrefix, "io.nats.jetstream.api.v1.stream_msg_delete_request")
	RegisterWildcardType(api.JSApiMsgDelete, "io.nats.jetstream.api.v1.stream_msg_delete_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_msg_delete_response", func() any { return &api.JSApiMsgDeleteResponse{} })
	RegisterResponseSubjectType(api.JSApiMsgDeletePrefix, "io.nats.jetstream.api.v1.stream_msg_delete_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_msg_get_request", func() any { return &api.JSApiMsgGetRequest{} })
	RegisterRequestSubjectType(api.JSApiMsgGetPrefix, "io.nats.jetstream.api.v1.stream_msg_get_request")
	RegisterWildcardType(api.JSApiMsgGet, "io.nats.jetstream.api.v1.stream_msg_get_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_msg_get_response", func() any { return &api.JSApiMsgGetResponse{} })
	RegisterResponseSubjectType(api.JSApiMsgGetPrefix, "io.nats.jetstream.api.v1.stream_msg_get_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_names_request", func() any { return &api.JSApiStreamNamesRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamNamesPrefix, "io.nats.jetstream.api.v1.stream_names_request")
	RegisterWildcardType(api.JSApiStreamNames, "io.nats.jetstream.api.v1.stream_names_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_names_response", func() any { return &api.JSApiStreamNamesResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamNamesPrefix, "io.nats.jetstream.api.v1.stream_names_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_purge_request", func() any { return &api.JSApiStreamPurgeRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamPurgePrefix, "io.nats.jetstream.api.v1.stream_purge_request")
	RegisterWildcardType(api.JSApiStreamPurge, "io.nats.jetstream.api.v1.stream_purge_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_purge_response", func() any { return &api.JSApiStreamPurgeResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamPurgePrefix, "io.nats.jetstream.api.v1.stream_purge_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_remove_peer_request", func() any { return &api.JSApiStreamRemovePeerRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamRemovePeerPrefix, "io.nats.jetstream.api.v1.stream_remove_peer_request")
	RegisterWildcardType(api.JSApiStreamRemovePeer, "io.nats.jetstream.api.v1.stream_remove_peer_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_remove_peer_response", func() any { return &api.JSApiStreamRemovePeerResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamRemovePeerPrefix, "io.nats.jetstream.api.v1.stream_remove_peer_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_restore_request", func() any { return &api.JSApiStreamRestoreRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamRestorePrefix, "io.nats.jetstream.api.v1.stream_restore_request")
	RegisterWildcardType(api.JSApiStreamRestore, "io.nats.jetstream.api.v1.stream_restore_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_restore_response", func() any { return &api.JSApiStreamRestoreResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamRestorePrefix, "io.nats.jetstream.api.v1.stream_restore_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_snapshot_request", func() any { return &api.JSApiStreamSnapshotRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamSnapshotPrefix, "io.nats.jetstream.api.v1.stream_snapshot_request")
	RegisterWildcardType(api.JSApiStreamSnapshot, "io.nats.jetstream.api.v1.stream_snapshot_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_snapshot_response", func() any { return &api.JSApiStreamSnapshotResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamSnapshotPrefix, "io.nats.jetstream.api.v1.stream_snapshot_response")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_update_request", func() any { return &api.JSApiStreamUpdateRequest{} })
	RegisterRequestSubjectType(api.JSApiStreamUpdatePrefix, "io.nats.jetstream.api.v1.stream_update_request")
	RegisterWildcardType(api.JSApiStreamUpdate, "io.nats.jetstream.api.v1.stream_update_request")
	RegisterTypeFactory("io.nats.jetstream.api.v1.stream_update_response", func() any { return &api.JSApiStreamUpdateResponse{} })
	RegisterResponseSubjectType(api.JSApiStreamUpdatePrefix, "io.nats.jetstream.api.v1.stream_update_response")
}
